import { Layout } from "@/components/layout"
import "@/styles/globals.css";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: 'Site-set',
  description: 'Generated by Next.js',
  openGraph:{
        title:'Site-set',
        description:'Venda seus produto como afiliado em um único lugar',
        url:'https://site-blog-khaki-gamma.vercel.app/og-image.jpg',
        siteName:'Site-set',
        locale:'pt_BR',
        type:'website',
        images:{
            url:'https://site-blog-khaki-gamma.vercel.app/og-image.jpg',
            width:800,
            height: 600,
            alt:'Site-set'
        }
    }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <Layout>
        {children}
      </Layout>  
      </body>
    </html>
  )
}
